wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700909490.65546
    t:
      1:
      - 1
      - 5
      - 11
      - 12
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      3:
      - 23
      4: 3.10.12
      5: 0.15.8
      6: 4.31.0
      8:
      - 5
