wandb_version: 1

model:
  desc: null
  value: TCN
learning_rate:
  desc: null
  value: 0.1
epochs:
  desc: null
  value: 400
batch_size:
  desc: null
  value: 64
shuffle:
  desc: null
  value: true
verbose:
  desc: null
  value: 1
patience:
  desc: null
  value: 20
dropout:
  desc: null
  value: 0.3
target:
  desc: null
  value: Close
feature_columns:
  desc: null
  value:
  - Open
  - High
  - Low
  - Close
  - Volume
NUM_CHANNELS:
  desc: null
  value:
  - 80
  - 80
  - 80
KERNEL:
  desc: null
  value: 7
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700761801.241616
    t:
      1:
      - 1
      - 11
      - 12
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.15.8
      6: 4.31.0
      8:
      - 1
      - 5
